name: batimgadai_app
description: Sistem Informasi Gadai Elektronik BATIM GADAI
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  dio: ^5.7.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Local Storage & Security
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.3.2
  crypto: ^3.0.3

  # Navigation
  go_router: ^14.6.2

  # UI & Font
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.10+1

  # Location
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1

  # Payment
  midtrans_sdk: ^1.2.0

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/illustrations/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
