name: batimgadai_app
description: Sistem Informasi Gadai Elektronik BATIM GADAI
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  dio: ^5.7.0

  # State management
  flutter_riverpod: ^2.6.1

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.3.2

  # Utils
  crypto: ^3.0.3
  device_info_plus: ^10.1.0
  intl: ^0.20.2
  url_launcher: ^6.3.0

  # Navigation
  go_router: ^14.6.2

  # UI
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3

  # Maps & Lokasi
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  permission_handler: ^11.3.1

  # Payment
  webview_flutter: ^4.10.0
  midtrans_sdk: ^1.2.0

  # Notifikasi & Background
  flutter_local_notifications: ^17.2.4
  workmanager: ^0.9.0+3
  timezone: ^0.9.4

  # Firebase
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/launcher_icon/icon_foreground.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/illustrations/
    - assets/icons/
    - assets/fonts/
    - assets/launcher_icon/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
